### PR TITLE
Added bindable properties width and height

### PR DESCRIPTION
**Pull request by Freeskier**
I think it is worth to add bindable properties width and height to shapes

### CODE REVIEW

**Comment by TeyKey1** [comment]
Hi @Freeskier 

I don't fully understand the use-case behind this addition. Currently, svelte-konva updates the node's bindable attributes on `dragend` and `transformend` events. Dragging does only lead to change of the `x` and `y` coordinates, while transforming of a node does not update the `width` and `height` attributes but only the `scaleX` and `scaleY` attributes (see the konva docs https://konvajs.org/docs/select_and_transform/Basic_demo.html). Thus, in the current state svelte-konva never updates the `width` and `height` attributes, so binding them has no effect.

**Comment by Freeskier** [comment]
@TeyKey1 I found a solution [here in docs](https://konvajs.org/docs/select_and_transform/Ignore_Stroke_On_Transform.html) for setting a width/height instead of a scale 
`      // first way to skip stroke resize, is just by resetting scale
      // and setting width/height instead
      rect1.on('transform', () => {
        rect1.setAttrs({
          width: Math.max(rect1.width() * rect1.scaleX(), 5),
          height: Math.max(rect1.height() * rect1.scaleY(), 5),
          scaleX: 1,
          scaleY: 1,
        });
      });`
which in my case was needed to skip scale  in favour of width/height. I can manage with setting attrbiutes of width/height tho, but  I find it more comfortable to bind it.

**Comment by TeyKey1** [comment]
Yes, this would be the recommended way to do the scale to width/height conversion in konva if it is required. While this _could_ be done by svelte-konva automatically, I'm not in favor of adding this functionality into the library as it basically locks the end user into this specific way of using konva. By not implementing such a feature, the library user stays much more flexible in which way they want to handle the scale or width/height attributes in case of transformation. 

To my knowledge, vue-konva as well as react-konva also give the end user the freedom to decide on how to handle this by not doing any automatic conversions.

**Comment by Freeskier** [comment]
Gotcha, dont get me wrong, I'm not pushing you into. I just thought that marking it as a `$bindable()` property does not break anything. It just expands possibilities because you can still pass values the same way and it continues to worke the same. Just anybody who wants to bind it - will do. If it's not convincing you of course I understand this, you can close PR. Thank you for reply :)

**Comment by TeyKey1** [comment]
> I just thought that marking it as a $bindable() property does not break anything.

Yes, but it also has no effect at all if implemented with the current code of this PR, as neither svelte-konva nor Konva update width or height automatically. There is no reactivity in place for this to happen.

> It just expands possibilities because you can still pass values the same way and it continues to worke the same. Just anybody who wants to bind it - will do.

This is not true. The implementation of such a feature would require svelte-konva to do something along the lines of this inside `onMount` of each transformable node to make width and height reactive:
```js
handle.on('transform', () => {
    if (width !== undefined) {
	    width = attrs.scaleX * attrs.width;
    
	    if (scaleX !== undefined) {
		    scaleX = 1;
	    } else {
		    handle.setAttr('scaleX', 1);
	    }
    }
    if (height !== undefined) {
	    height = attrs.scaleY * attrs.height;
    
	    if (scaleY !== undefined) {
		    scaleY = 1;
	    } else {
		    handle.setAttr('scaleY', 1);
	    }
    }
    
    handle.cache();
});
```

If correctly implemented, this feature will be breaking, as anything that used to bind `scaleX` and/or `scaleY` props or used them directly on the Konva node using `node.scaleX()` etc. will break as the scale property is now fixed to 1 and never changes.

So for the meantime, I suggest doing this on the user side:

```svelte
<script>
  import { Stage, Layer, Rect, Transformer } from "svelte-konva";
  import { onMount, tick } from "svelte";

  let rectangle = $state();
  let transformer = $state();
  let color = $state("green");

  onMount(async () => {
    await tick();

    transformer.handle.nodes([rectangle.handle]);
  });

  let rectWidth = $state(50);
  let rectHeight = $state(50);

  let rectScaleX = $state(1);
  let rectScaleY = $state(1);

  function scaleToWidthAndHeight(e) {
    rectWidth = rectWidth * rectScaleX;
    rectHeight = rectHeight * rectScaleY;

    rectScaleX = 1;
    rectScaleY = 1;
  }

</script>

<Stage width={window.innerWidth} height={window.innerHeight}>
  <Layer>
    <Rect
      x={10}
      y={10}
      width={rectWidth}
      height={rectHeight}
      bind:scaleX={rectScaleX}
      bind:scaleY={rectScaleY}
      fill={color}
      bind:this={rectangle}
      draggable
      ontransformend={scaleToWidthAndHeight}
    />

    <Transformer bind:this={transformer}></Transformer>
  </Layer>
</Stage>
```

Closing this PR for now. If there happens to be popular demand for such a functionality in the future, we can reopen and think about a possible implementation for this.

**Pull request closed without merging**
